name: Upgrade dependencies

on: push

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
          ssh-key: ${{ secrets.BUMP_DEPENDENCIES_RSA }}
      - run: |
          yarn upgrade
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -B chore/dependencies
          git add .
          git diff --quiet --exit-code
          git commit -m "bump dependencies"
          git push --set-upstream origin chore/dependencies --force
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'chore/dependencies',
              base: 'main',
              title: 'chore: bump dependencies',
              maintainer_can_modify: true,
            });
